name: linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  git_clone:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1
      
    - name: install
      run: make install
      
    - name: lint
      run: make lint
